"on":
    push:
        branches:
            - main
name: Deploy to mcp-server
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: mcp-server
                PORTER_CLUSTER: "4151"
                PORTER_DEPLOYMENT_TARGET_ID: 2222091e-eed3-40a8-bb60-86728b54d56f
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PROJECT: "11208"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_11208_1181459491 }}
